// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkAPI.Models;

namespace ParkAPI.Migrations
{
    [DbContext(typeof(ParkAPIContext))]
    [Migration("20210122222812_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParkAPI.Models.NationalPark", b =>
                {
                    b.Property<int>("NationalParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<string>("TotalArea")
                        .IsRequired();

                    b.Property<string>("Website")
                        .IsRequired();

                    b.HasKey("NationalParkId");

                    b.ToTable("NationalParks");

                    b.HasData(
                        new
                        {
                            NationalParkId = 1,
                            Address = "PO Box 129 Grand Canyon, AZ 86023",
                            Name = "Grand Canyon National Park",
                            State = "Arizona",
                            TotalArea = "1902 mi²",
                            Website = "https://www.nps.gov/grca/index.htm"
                        },
                        new
                        {
                            NationalParkId = 2,
                            Address = "P.O. Box 579 Death Valley, CA 92328",
                            Name = "Death Valley National Park",
                            State = "California",
                            TotalArea = "5,270 mi²",
                            Website = "https://www.nps.gov/deva/index.htm"
                        },
                        new
                        {
                            NationalParkId = 3,
                            Address = "PO Box 577 Yosemite, CA 95389",
                            Name = "Yosemite National Park",
                            State = "California",
                            TotalArea = "1,169 mi²",
                            Website = "https://www.nps.gov/yose/index.htm"
                        },
                        new
                        {
                            NationalParkId = 4,
                            Address = "PO Box 7 Crater Lake , OR 97604",
                            Name = "Crater Lake National Park",
                            State = "Oregon",
                            TotalArea = "20.6 mi²",
                            Website = "https://www.nps.gov/crla/index.htm"
                        },
                        new
                        {
                            NationalParkId = 5,
                            Address = "HC 70, PO Box15 Torrey, UT 84775",
                            Name = "Capitol Reef National Park",
                            State = "Utah",
                            TotalArea = "378 mi²",
                            Website = "https://www.nps.gov/care/index.htm"
                        });
                });

            modelBuilder.Entity("ParkAPI.Models.StatePark", b =>
                {
                    b.Property<int>("StateParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.Property<string>("TotalArea")
                        .IsRequired();

                    b.Property<string>("Website")
                        .IsRequired();

                    b.HasKey("StateParkId");

                    b.ToTable("StateParks");

                    b.HasData(
                        new
                        {
                            StateParkId = 1,
                            Address = "6109 N. Apache Trail Apache Junction, AZ 85119",
                            Name = "Lost Dutchman State Park",
                            State = "Arizona",
                            TotalArea = ".5 mi²",
                            Website = "https://azstateparks.com/lost-dutchman/"
                        },
                        new
                        {
                            StateParkId = 2,
                            Address = "UT-313, Moab, UT 84532",
                            Name = "Dead Horse Point State Park",
                            State = "Utah",
                            TotalArea = "8.4 mi²",
                            Website = "https://stateparks.utah.gov/parks/dead-horse/"
                        },
                        new
                        {
                            StateParkId = 3,
                            Address = " 44°21'58.01N, 121° 8'13.32W or 44.367612, -121.138988",
                            Name = "Smith Rock State Park",
                            State = "Oregon",
                            TotalArea = "1.1 mi²",
                            Website = "https://stateparks.oregon.gov/index.cfm?do=park.profile&parkId=36"
                        },
                        new
                        {
                            StateParkId = 4,
                            Address = "138 Emerald Bay Rd, South Lake Tahoe, CA 96150",
                            Name = "Emerald Bay State Park",
                            State = "California",
                            TotalArea = "2.4 mi²",
                            Website = "https://www.parks.ca.gov/?page_id=506"
                        },
                        new
                        {
                            StateParkId = 5,
                            Address = "4050 Red Rock Loop Rd Sedona, AZ 86336",
                            Name = "Red Rock State Park",
                            State = "Arizona",
                            TotalArea = ".45 mi²",
                            Website = "https://azstateparks.com/red-rock/"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
